<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="Testcontainers.MsSql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\backend\src\Fut7Fantasy.Api\Fut7Fantasy.Api.csproj" />
    <ProjectReference Include="..\..\..\src\backend\src\Fut7Fantasy.Demo\Fut7Fantasy.Demo.csproj" />
  </ItemGroup>

</Project>
