// <auto-generated />
using System;
using Fut7Fantasy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fut7Fantasy.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(Fut7FantasyDbContext))]
    [Migration("20260922131254_Notifications")]
    partial class Notifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fut7Fantasy.Domain.Competitions.AthleteAppearance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DidPlay")
                        .HasColumnType("bit");

                    b.Property<int>("GoalsConceded")
                        .HasColumnType("int");

                    b.Property<Guid>("MatchSheetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("PlayedAsGoalkeeper")
                        .HasColumnType("bit");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<Guid>("RealTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("RealTeamId");

                    b.HasIndex("CompetitionId", "MatchSheetId");

                    b.HasIndex("MatchSheetId", "AthleteId")
                        .IsUnique();

                    b.ToTable("AthleteAppearances", "competitions", t =>
                        {
                            t.HasCheckConstraint("CK_AthleteAppearances_GoalsConceded", "[GoalsConceded] BETWEEN 0 AND 99");
                        });
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Competitions.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CorrectionWindowBusinessDays")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MarketCloseLeadTime")
                        .HasColumnType("int")
                        .HasColumnName("MarketCloseLeadTimeMinutes");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("ModalityProfileVersion")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RegistrationDeadline")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ResultsSlaBusinessDays")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Slug")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasFilter("[Slug] IS NOT NULL");

                    b.HasIndex("Status");

                    b.HasIndex("OrganizationId", "UpdatedAt");

                    b.ToTable("Competitions", "competitions", t =>
                        {
                            t.HasCheckConstraint("CK_Competitions_CorrectionWindowBusinessDays", "[CorrectionWindowBusinessDays] BETWEEN 1 AND 10");

                            t.HasCheckConstraint("CK_Competitions_MarketCloseLeadTimeMinutes", "[MarketCloseLeadTimeMinutes] BETWEEN 0 AND 4320");

                            t.HasCheckConstraint("CK_Competitions_PublishedHasSlug", "[Status] <> 'Published' OR [Slug] IS NOT NULL");

                            t.HasCheckConstraint("CK_Competitions_ResultsSlaBusinessDays", "[ResultsSlaBusinessDays] BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Competitions.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("KickoffAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("StageId");

                    b.HasIndex("CompetitionId", "KickoffAt");

                    b.HasIndex("RoundId", "KickoffAt");

                    b.ToTable("Matches", "competitions");
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Competitions.MatchSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AwayScore")
                        .HasColumnType("int");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("HomeScore")
                        .HasColumnType("int");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.HasIndex("CompetitionId", "MatchId")
                        .IsUnique();

                    b.ToTable("MatchSheets", "competitions", t =>
                        {
                            t.HasCheckConstraint("CK_MatchSheets_AwayScore", "[AwayScore] BETWEEN 0 AND 99");

                            t.HasCheckConstraint("CK_MatchSheets_HomeScore", "[HomeScore] BETWEEN 0 AND 99");
                        });
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Competitions.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ConsolidatesAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CorrectionReason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FirstKickoffAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("MarketCloseAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ReopenedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId", "Sequence");

                    b.ToTable("Rounds", "competitions", t =>
                        {
                            t.HasCheckConstraint("CK_Rounds_OpenMarketHasCloseAt", "[Status] <> 'MarketOpen' OR [MarketCloseAt] IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Competitions.Stage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("_tiebreakers")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Tiebreakers");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId", "Sequence");

                    b.ToTable("Stages", "competitions", t =>
                        {
                            t.HasCheckConstraint("CK_Stages_Sequence", "[Sequence] BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Competitions.StageGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("StageGroups", "competitions");
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Competitions.StageParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RealTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StageGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("RealTeamId");

                    b.HasIndex("StageGroupId");

                    b.HasIndex("StageId", "RealTeamId")
                        .IsUnique();

                    b.ToTable("StageParticipants", "competitions");
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Competitions.StatEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MatchSheetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("RedCardReason")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("CompetitionId", "MatchSheetId");

                    b.HasIndex("MatchSheetId", "AthleteId", "Type")
                        .IsUnique();

                    b.ToTable("StatEvents", "competitions", t =>
                        {
                            t.HasCheckConstraint("CK_StatEvents_Quantity", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Fantasy.FantasyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Balance")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<Guid?>("CaptainAthleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CompetitionId", "UserId")
                        .IsUnique();

                    b.ToTable("Entries", "fantasy", t =>
                        {
                            t.HasCheckConstraint("CK_Entries_Balance", "[Balance] >= 0");
                        });
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Fantasy.LineupSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaptainAthleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("MarketClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MaxAthletesPerTeam")
                        .HasColumnType("int");

                    b.Property<int>("MaxStartersPerTeam")
                        .HasColumnType("int");

                    b.Property<int>("ModalityProfileVersion")
                        .HasColumnType("int");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.HasIndex("EntryId", "RoundId")
                        .IsUnique();

                    b.ToTable("LineupSnapshots", "fantasy");
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Fantasy.LineupSnapshotSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Position")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("Price")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("RealTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RealTeamName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId", "Kind", "AssetId")
                        .IsUnique();

                    b.ToTable("LineupSnapshotSlots", "fantasy");
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Fantasy.SquadSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Position")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("RealTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("RealTeamId");

                    b.HasIndex("Kind", "AssetId");

                    b.HasIndex("EntryId", "Kind", "AssetId")
                        .IsUnique();

                    b.ToTable("SquadSlots", "fantasy");
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("Revision")
                        .HasColumnType("int");

                    b.Property<Guid?>("RoundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("RoundId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.HasIndex("UserId", "RoundId", "Revision")
                        .IsUnique()
                        .HasFilter("[RoundId] IS NOT NULL");

                    b.ToTable("Notifications", "notifications");
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Organizations", "organizations");
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Organizations.OrganizationInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InvitedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("InvitedEmailNormalized")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedByUserId");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "InvitedEmailNormalized", "Status");

                    b.ToTable("OrganizationInvitations", "organizations");
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Organizations.OrganizationMember", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("OrganizationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("OrganizationMembers", "organizations");
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.PlatformAdministration.AdministrativeAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("TargetId", "OccurredAt");

                    b.ToTable("AdministrativeAuditEntries", "platform");
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.PlatformAdministration.OrganizerApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicantUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantUserId")
                        .IsUnique()
                        .HasFilter("[Status] = N'Pending'");

                    b.HasIndex("DecidedByUserId");

                    b.HasIndex("OrganizationId")
                        .IsUnique()
                        .HasFilter("[OrganizationId] IS NOT NULL");

                    b.HasIndex("Status", "SubmittedAt");

                    b.ToTable("OrganizerApplications", "platform");
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Scoring.AssetPriceChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Average")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<Guid>("CalculationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Difference")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("NewPrice")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PreviousPrice")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Variation")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "AssetId");

                    b.HasIndex("CalculationId", "Kind", "AssetId")
                        .IsUnique();

                    b.ToTable("AssetPriceChanges", "scoring", t =>
                        {
                            t.HasCheckConstraint("CK_AssetPriceChanges_NewPrice", "[NewPrice] >= 1 AND [NewPrice] <= 30");
                        });
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Scoring.AthleteRoundResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CalculationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Played")
                        .HasColumnType("bit");

                    b.Property<decimal>("Points")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("RealTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CalculationId", "AthleteId")
                        .IsUnique();

                    b.ToTable("AthleteRoundResults", "scoring");
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Scoring.AthleteScoreLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CalculationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Points")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CalculationId", "AthleteId", "MatchId", "Item")
                        .IsUnique();

                    b.ToTable("AthleteScoreLines", "scoring");
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Scoring.CoachRoundResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CalculationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Played")
                        .HasColumnType("bit");

                    b.Property<decimal>("Points")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<Guid>("RealTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CalculationId", "CoachId")
                        .IsUnique();

                    b.ToTable("CoachRoundResults", "scoring");
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Scoring.EntryRoundResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CalculationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CaptainBonus")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Total")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.HasIndex("CalculationId", "EntryId")
                        .IsUnique();

                    b.ToTable("EntryRoundResults", "scoring");
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Scoring.EntrySlotResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CalculationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Counts")
                        .HasColumnType("bit");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("Played")
                        .HasColumnType("bit");

                    b.Property<decimal>("Points")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("Position")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid?>("ReplacedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Replaces")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("CalculationId", "EntryId", "Kind", "AssetId")
                        .IsUnique();

                    b.ToTable("EntrySlotResults", "scoring");
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Scoring.PositionAverage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Average")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<Guid>("CalculationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Position")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("CalculationId", "Kind", "Position")
                        .IsUnique()
                        .HasFilter("[Position] IS NOT NULL");

                    b.ToTable("PositionAverages", "scoring");
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Scoring.RoundCalculation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CalculatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrectionReason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ScoringRuleSetVersion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CalculatedBy");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("RoundId", "Revision")
                        .IsUnique();

                    b.ToTable("RoundCalculations", "scoring", t =>
                        {
                            t.HasCheckConstraint("CK_RoundCalculations_Revision", "[Revision] >= 1");
                        });
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.SportsCatalog.Athlete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FirstMarketAvailableAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SportingName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId", "SportingName")
                        .IsUnique();

                    b.ToTable("Athletes", "sports_catalog");
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.SportsCatalog.Coach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset?>("FirstMarketAvailableAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("InitialPriceOverride")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("PriceTier")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("RealTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("RealTeamId")
                        .IsUnique();

                    b.HasIndex("CompetitionId", "RealTeamId");

                    b.ToTable("Coaches", "sports_catalog", t =>
                        {
                            t.HasCheckConstraint("CK_Coaches_InitialPriceOverride", "[InitialPriceOverride] IS NULL OR [InitialPriceOverride] BETWEEN 1 AND 30");
                        });
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.SportsCatalog.RealTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId", "ArchivedAt");

                    b.HasIndex("CompetitionId", "Name")
                        .IsUnique();

                    b.ToTable("RealTeams", "sports_catalog");
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.SportsCatalog.RosterRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("InitialPriceOverride")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("PriceTier")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("RealTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId")
                        .IsUnique();

                    b.HasIndex("RealTeamId");

                    b.HasIndex("CompetitionId", "RealTeamId", "Status");

                    b.ToTable("RosterRegistrations", "sports_catalog", t =>
                        {
                            t.HasCheckConstraint("CK_RosterRegistrations_InitialPriceOverride", "[InitialPriceOverride] IS NULL OR [InitialPriceOverride] BETWEEN 1 AND 30");
                        });
                });

            modelBuilder.Entity("Fut7Fantasy.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", "identity");
                });

            modelBuilder.Entity("Fut7Fantasy.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", "identity");
                });

            modelBuilder.Entity("Fut7Fantasy.Infrastructure.Persistence.StartupRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt")
                        .IsDescending();

                    b.ToTable("StartupRecords", "app");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "identity");
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Competitions.AthleteAppearance", b =>
                {
                    b.HasOne("Fut7Fantasy.Domain.SportsCatalog.Athlete", null)
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fut7Fantasy.Domain.Competitions.MatchSheet", null)
                        .WithMany()
                        .HasForeignKey("MatchSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fut7Fantasy.Domain.SportsCatalog.RealTeam", null)
                        .WithMany()
                        .HasForeignKey("RealTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Competitions.Competition", b =>
                {
                    b.HasOne("Fut7Fantasy.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fut7Fantasy.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Competitions.Match", b =>
                {
                    b.HasOne("Fut7Fantasy.Domain.SportsCatalog.RealTeam", null)
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fut7Fantasy.Domain.Competitions.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fut7Fantasy.Domain.SportsCatalog.RealTeam", null)
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fut7Fantasy.Domain.Competitions.Round", null)
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fut7Fantasy.Domain.Competitions.Stage", null)
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Competitions.MatchSheet", b =>
                {
                    b.HasOne("Fut7Fantasy.Domain.Competitions.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fut7Fantasy.Domain.Competitions.Match", null)
                        .WithOne()
                        .HasForeignKey("Fut7Fantasy.Domain.Competitions.MatchSheet", "MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Competitions.Round", b =>
                {
                    b.HasOne("Fut7Fantasy.Domain.Competitions.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Competitions.Stage", b =>
                {
                    b.HasOne("Fut7Fantasy.Domain.Competitions.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Competitions.StageGroup", b =>
                {
                    b.HasOne("Fut7Fantasy.Domain.Competitions.Stage", null)
                        .WithMany("_groups")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Competitions.StageParticipant", b =>
                {
                    b.HasOne("Fut7Fantasy.Domain.SportsCatalog.RealTeam", null)
                        .WithMany()
                        .HasForeignKey("RealTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fut7Fantasy.Domain.Competitions.StageGroup", null)
                        .WithMany()
                        .HasForeignKey("StageGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fut7Fantasy.Domain.Competitions.Stage", null)
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Competitions.StatEvent", b =>
                {
                    b.HasOne("Fut7Fantasy.Domain.SportsCatalog.Athlete", null)
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fut7Fantasy.Domain.Competitions.MatchSheet", null)
                        .WithMany()
                        .HasForeignKey("MatchSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Fantasy.FantasyEntry", b =>
                {
                    b.HasOne("Fut7Fantasy.Domain.Competitions.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fut7Fantasy.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Fantasy.LineupSnapshot", b =>
                {
                    b.HasOne("Fut7Fantasy.Domain.Fantasy.FantasyEntry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fut7Fantasy.Domain.Competitions.Round", null)
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Fantasy.LineupSnapshotSlot", b =>
                {
                    b.HasOne("Fut7Fantasy.Domain.Fantasy.LineupSnapshot", null)
                        .WithMany("Slots")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Fantasy.SquadSlot", b =>
                {
                    b.HasOne("Fut7Fantasy.Domain.Fantasy.FantasyEntry", null)
                        .WithMany("Slots")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fut7Fantasy.Domain.SportsCatalog.RealTeam", null)
                        .WithMany()
                        .HasForeignKey("RealTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Notifications.Notification", b =>
                {
                    b.HasOne("Fut7Fantasy.Domain.Competitions.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fut7Fantasy.Domain.Competitions.Round", null)
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Fut7Fantasy.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Organizations.OrganizationInvitation", b =>
                {
                    b.HasOne("Fut7Fantasy.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("AcceptedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fut7Fantasy.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fut7Fantasy.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Organizations.OrganizationMember", b =>
                {
                    b.HasOne("Fut7Fantasy.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fut7Fantasy.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.PlatformAdministration.AdministrativeAuditEntry", b =>
                {
                    b.HasOne("Fut7Fantasy.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.PlatformAdministration.OrganizerApplication", b =>
                {
                    b.HasOne("Fut7Fantasy.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ApplicantUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fut7Fantasy.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("DecidedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fut7Fantasy.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Scoring.AssetPriceChange", b =>
                {
                    b.HasOne("Fut7Fantasy.Domain.Scoring.RoundCalculation", null)
                        .WithMany("Prices")
                        .HasForeignKey("CalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Scoring.AthleteRoundResult", b =>
                {
                    b.HasOne("Fut7Fantasy.Domain.Scoring.RoundCalculation", null)
                        .WithMany("Athletes")
                        .HasForeignKey("CalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Scoring.AthleteScoreLine", b =>
                {
                    b.HasOne("Fut7Fantasy.Domain.Scoring.RoundCalculation", null)
                        .WithMany("AthleteLines")
                        .HasForeignKey("CalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Scoring.CoachRoundResult", b =>
                {
                    b.HasOne("Fut7Fantasy.Domain.Scoring.RoundCalculation", null)
                        .WithMany("Coaches")
                        .HasForeignKey("CalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Scoring.EntryRoundResult", b =>
                {
                    b.HasOne("Fut7Fantasy.Domain.Scoring.RoundCalculation", null)
                        .WithMany("Entries")
                        .HasForeignKey("CalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fut7Fantasy.Domain.Fantasy.FantasyEntry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Scoring.EntrySlotResult", b =>
                {
                    b.HasOne("Fut7Fantasy.Domain.Scoring.RoundCalculation", null)
                        .WithMany("EntrySlots")
                        .HasForeignKey("CalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Scoring.PositionAverage", b =>
                {
                    b.HasOne("Fut7Fantasy.Domain.Scoring.RoundCalculation", null)
                        .WithMany("Averages")
                        .HasForeignKey("CalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Scoring.RoundCalculation", b =>
                {
                    b.HasOne("Fut7Fantasy.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CalculatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fut7Fantasy.Domain.Competitions.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fut7Fantasy.Domain.Competitions.Round", null)
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.SportsCatalog.Athlete", b =>
                {
                    b.HasOne("Fut7Fantasy.Domain.Competitions.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.SportsCatalog.Coach", b =>
                {
                    b.HasOne("Fut7Fantasy.Domain.Competitions.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fut7Fantasy.Domain.SportsCatalog.RealTeam", null)
                        .WithOne()
                        .HasForeignKey("Fut7Fantasy.Domain.SportsCatalog.Coach", "RealTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.SportsCatalog.RealTeam", b =>
                {
                    b.HasOne("Fut7Fantasy.Domain.Competitions.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.SportsCatalog.RosterRegistration", b =>
                {
                    b.HasOne("Fut7Fantasy.Domain.SportsCatalog.Athlete", null)
                        .WithOne()
                        .HasForeignKey("Fut7Fantasy.Domain.SportsCatalog.RosterRegistration", "AthleteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fut7Fantasy.Domain.Competitions.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fut7Fantasy.Domain.SportsCatalog.RealTeam", null)
                        .WithMany()
                        .HasForeignKey("RealTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Fut7Fantasy.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Fut7Fantasy.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Fut7Fantasy.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Fut7Fantasy.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fut7Fantasy.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Fut7Fantasy.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Competitions.Stage", b =>
                {
                    b.Navigation("_groups");
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Fantasy.FantasyEntry", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Fantasy.LineupSnapshot", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("Fut7Fantasy.Domain.Scoring.RoundCalculation", b =>
                {
                    b.Navigation("AthleteLines");

                    b.Navigation("Athletes");

                    b.Navigation("Averages");

                    b.Navigation("Coaches");

                    b.Navigation("Entries");

                    b.Navigation("EntrySlots");

                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
